debug: add pwd and file check to Build step

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -158,6 +158,8 @@ jobs:
         working-directory: onnxruntime
         shell: bash
         run: |
+          echo "BUILD PWD=$(pwd)"
+          ls cmake/cpuinfo_ohos_stub.c 2>/dev/null && echo "STUB FOUND in BUILD" || echo "STUB NOT FOUND in BUILD"
           mkdir build-shared && cd build-shared
 
           OHOS_NATIVE=$GITHUB_WORKSPACE/command-line-tools/sdk/default/openharmony/native
